name: dinosaur_quiz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  clipboard: ^0.1.3
  flutter:
    sdk: flutter
  recase: ^4.1.0
  flex_color_scheme: ^6.1.2
  flutter_launcher_icons: ^0.12.0
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.2
  font_awesome_flutter: ^10.4.0
  riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.1.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/text/
    - assets/images/dinosaurs
    - assets/images/space

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Merienda
      fonts:
        - asset: assets/fonts/Merienda/static/Merienda-Regular.ttf
    - family: DinoSauce
      fonts:
        - asset: assets/fonts/dinosauce/DinosauceFont-Regular.ttf
    - family: Erasaur
      fonts:
        - asset: assets/fonts/erasaur/Erasaur-wjZ9.otf
    - family: Induction
      fonts:
        - asset: assets/fonts/Induction/Induction.otf
    - family: Andromeda
      fonts:
        - asset: assets/fonts/Andromeda/AndromedaTV.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
